# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.0
        environment:
          BUNDLER_VERSION: 2.0.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies for test
          command: |
            # below command for updating bundler version in circleci/ruby:2.5.0
            sudo gem update --system
            sudo gem uninstall bundler
            sudo rm /usr/local/bin/bundle
            sudo rm /usr/local/bin/bundler
            sudo gem install bundler:2.0.1
            bundle install --without development --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      - run:
          name: run test
          command: |
            mkdir /tmp/test-results
            rspec --format RspecJunitFormatter --out /tmp/test-results/rspec.xml

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      # prepare Lambda pkg
      - run: zip -r seanmctoday.zip lambda.rb vendor/ lib/
      - save_cache:
          paths:
            - seanmctoday.zip
          key: lambda-pkg

  deploy:
    requires:
      - build
    filters:
      branches:
        only: master

    docker:
      - image: wilson208/circleci-awscli

    steps:
      - restore_cache:
          keys:
            - lambda-pkg
 
      - run: aws lambda update-function-code --function-name seanmctoday-telegram --zip-file fileb://seanmctoday.zip
